Week1.c.lists: list.h File Reference
list.h File Reference
Macros
#define STATUS_OK 0
#define STATUS_ERR -1
Typedefs
typedef int status_t
Functions
struct list * new_list ()
int list_size (struct list *list)
void * list_element_at (struct list *list, int i)
void list_append (struct list *list, void *element)
void list_prepend (struct list *list, void *element)
int list_insert_before_element (struct list *list, void *mark, void *element)
int list_insert_after_element (struct list *list, void *mark, void *element)
void list_insert_before_index (struct list *list, int i, void *element)
void list_insert_after_index (struct list *list, int i, void *element)
void * list_remove_at_index (struct list *list, int i)
int list_remove_ (struct list *list, void *element)
Macro Definition Documentation
#define STATUS_ERR -1
Definition at line 13 of file list.h.
Referenced by close(), read(), and write().
#define STATUS_OK 0
Definition at line 12 of file list.h.
Typedef Documentation
typedef int status_t
Definition at line 11 of file list.h.
Function Documentation
void list_append (struct list * list, void * element)
Attach an element at the end of the list
Parameters
list : the pointer to the list
element : the element that is supposed to be attached
Definition at line 33 of file list.c.
References list_entry::elem, list::head, list_insert_after_index(), and list::size.
Referenced by main(), parse_properties(), random_string_insert_test(), random_struct_insert_test(), and write().
void* list_element_at (struct list * list, int i)
Returns the element at the position passed as argument
Parameters
list : the pointer to the list
i : the position , 0 is the first position
Definition at line 60 of file list.c.
References list_entry::elem, list::head, and list_entry::next.
Referenced by print_list(), print_properties(), print_stream(), random_string_insert_test(), and random_struct_insert_test().
int list_insert_after_element (struct list * list, void * mark, void * element)
Inserts an element to the list just after the mark
Parameters
list : the pointer to the list
mark : the element after which new element should be inserted
element : the element to be added
Returns
Definition at line 100 of file list.c.
References list_entry::elem, list::head, list_entry::next, and list::size.
void list_insert_after_index (struct list * list, int i, void * element)
Insert an element after the index i
Parameters
list : the pointer to the list
i : the index , 0 is the first index
element : the element to be added
Definition at line 151 of file list.c.
References list_entry::elem, list::head, list_entry::next, and list::size.
Referenced by list_append().
int list_insert_before_element (struct list * list, void * mark, void * element)
Inserts an element to the list just before the mark
Parameters
list : the pointer to the list
mark : the element before which new element should be inserted
element : the element to be added
Returns
:
Definition at line 68 of file list.c.
References list_entry::elem, list::head, list_entry::next, and list::size.
void list_insert_before_index (struct list * list, int i, void * element)
Insert an element before the index i
Parameters
list : the pointer to the list
i : the index , 0 is the first index
element : the element to be added
Definition at line 124 of file list.c.
References list_entry::elem, list::head, list_entry::next, and list::size.
Referenced by list_prepend(), random_string_insert_test(), and random_struct_insert_test().
void list_prepend (struct list * list, void * element)
Attach an element at the front of the list
Parameters
list : the pointer to the list
element : the element to be added
Definition at line 47 of file list.c.
References list_entry::elem, list::head, list_insert_before_index(), and list::size.
Referenced by read().
int list_remove_ (struct list * list, void * element)
Find the element and remove it
Parameters
list : the pointer to the list
element : the element to be removed
Returns
Definition at line 197 of file list.c.
References list_entry::elem, list::head, list_entry::next, and list::size.
void* list_remove_at_index (struct list * list, int i)
remove the element at the index i
Parameters
list : the pointer to the list
i : the index i , 0 is the first index
Returns
: the pointer to the element or NULL if list is empty
Definition at line 171 of file list.c.
References list_entry::elem, list::head, list_size(), list_entry::next, and list::size.
Referenced by close(), main(), and read().
int list_size (struct list * list)
Returns the size of a given list
Parameters
list : the pointer to the list
Returns
int : size
Definition at line 29 of file list.c.
References list::size.
Referenced by close(), list_remove_at_index(), print_list(), print_properties(), print_stream(), and read().
struct list* new_list ()
Definition at line 24 of file list.c.
Referenced by main(), open(), parse_properties(), and run_all_tests().