Week1.c.lists: list.c File Reference
list.c File Reference
#include <stddef.h>
#include "stdint.h"
#include <stdlib.h>
#include <string.h>
#include "list.h"
Data Structures
struct list_entry
struct list
Functions
struct list * new_list ()
int list_size (struct list *list)
void list_append (struct list *list, void *element)
void list_prepend (struct list *list, void *element)
void * list_element_at (struct list *list, int idx)
int list_insert_before_element (struct list *list, void *mark, void *element)
int list_insert_after_element (struct list *list, void *mark, void *element)
void list_insert_before_index (struct list *list, int idx, void *element)
void list_insert_after_index (struct list *list, int idx, void *element)
void * list_remove_at_index (struct list *list, int idx)
int list_remove_ (struct list *list, void *mark)
Function Documentation
void list_append (struct list * list, void * element)
Attach an element at the end of the list
Parameters
list : the pointer to the list
element : the element that is supposed to be attached
Definition at line 33 of file list.c.
References list_entry::elem, list::head, list_insert_after_index(), and list::size.
Referenced by main(), parse_properties(), random_string_insert_test(), and random_struct_insert_test().
void* list_element_at (struct list * list, int i)
Returns the element at the position passed as argument
Parameters
list : the pointer to the list
i : the position
Definition at line 60 of file list.c.
References list_entry::elem, list::head, and list_entry::next.
Referenced by print_list(), print_properties(), random_string_insert_test(), and random_struct_insert_test().
int list_insert_after_element (struct list * list, void * mark, void * element)
Inserts an element to the list just after the mark
Parameters
list : the pointer to the list
mark : the element after which new element should be inserted
element : the element to be added
Returns
Definition at line 100 of file list.c.
References list_entry::elem, list::head, list_entry::next, and list::size.
void list_insert_after_index (struct list * list, int i, void * element)
Insert an element after the index i
Parameters
list : the pointer to the list
i : the index
element : the element to be added
Definition at line 151 of file list.c.
References list_entry::elem, list::head, list_entry::next, and list::size.
Referenced by list_append().
int list_insert_before_element (struct list * list, void * mark, void * element)
Inserts an element to the list just before the mark
Parameters
list : the pointer to the list
mark : the element before which new element should be inserted
element : the element to be added
Returns
:
Definition at line 68 of file list.c.
References list_entry::elem, list::head, list_entry::next, and list::size.
void list_insert_before_index (struct list * list, int i, void * element)
Insert an element before the index i
Parameters
list : the pointer to the list
i : the index
element : the element to be added
Definition at line 124 of file list.c.
References list_entry::elem, list::head, list_entry::next, and list::size.
Referenced by list_prepend(), random_string_insert_test(), and random_struct_insert_test().
void list_prepend (struct list * list, void * element)
Attach an element at the front of the list
Parameters
list : the pointer to the list
element : the element to be added
Definition at line 47 of file list.c.
References list_entry::elem, list::head, list_insert_before_index(), and list::size.
int list_remove_ (struct list * list, void * element)
Find the element and remove it
Parameters
list : the pointer to the list
element : the element to be removed
Returns
Definition at line 193 of file list.c.
References list_entry::elem, list::head, list_entry::next, and list::size.
void* list_remove_at_index (struct list * list, int i)
remove the element at the index i
Parameters
list : the pointer to the list
i : the index i
Definition at line 171 of file list.c.
References list_entry::elem, list::head, list_entry::next, and list::size.
Referenced by main().
int list_size (struct list * list)
Returns the size of a given list
Parameters
list : the pointer to the list
Returns
int : size
Definition at line 29 of file list.c.
References list::size.
Referenced by print_list(), and print_properties().
struct list* new_list ()
Definition at line 24 of file list.c.
Referenced by main(), parse_properties(), and run_all_tests().