Week1.c.lists: props.h File Reference
props.h File Reference
Data Structures
struct property
struct properties
Functions
struct properties * parse_properties (char *chars)
void print_properties (struct properties *props)
Function Documentation
struct properties* parse_properties (char * chars)
Parameters
chars
Returns
Definition at line 65 of file props.c.
References list_append(), new_list(), property_parse(), and properties::props.
Referenced by basic_prop_test(), and perf_prop_test().
void print_properties (struct properties * props)
Definition at line 78 of file props.c.
References property::key, list_element_at(), list_size(), properties::props, and property::value.
Referenced by basic_prop_test().