Week1.c.lists: props.c File Reference
props.c File Reference
#include <stddef.h>
#include "stdint.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "list.h"
#include "props.h"
Functions
char * property_parse (char *chars, struct property **ppt)
struct properties * parse_properties (char *chars)
void print_properties (struct properties *props)
Function Documentation
struct properties* parse_properties (char * chars)
Parameters
chars
Returns
Definition at line 65 of file props.c.
References list_append(), new_list(), property_parse(), and properties::props.
Referenced by basic_prop_test(), and perf_prop_test().
void print_properties (struct properties * props)
Definition at line 78 of file props.c.
References property::key, list_element_at(), list_size(), properties::props, and property::value.
Referenced by basic_prop_test().
char* property_parse (char * chars, struct property ** ppt)
Definition at line 16 of file props.c.
References property::key, and property::value.
Referenced by parse_properties().