Week1.c.lists: stream.h File Reference
stream.h File Reference
Data Structures
struct compartment
struct stream
Typedefs
typedef struct compartment compartment
typedef struct stream stream
Functions
stream * open ()
int write (stream *st, const char *buf, int buf_size)
int read (stream *st, char *buf, int read_size)
int close (stream *st)
Typedef Documentation
typedef struct compartment compartment
Definition at line 21 of file stream.h.
typedef struct stream stream
Definition at line 30 of file stream.h.
Function Documentation
int close (stream * st)
Closes the stream and deletes all compartments
Parameters
st : the stream to be closed
Returns
: 0 if closed successfully
Definition at line 99 of file stream.c.
References compartment::buffer, stream::comps, list_remove_at_index(), list_size(), and STATUS_ERR.
Referenced by main().
stream* open ()
This function opens a stream and returns a pointer to the same
Returns
: a pointer to the stream, NULL on error
Definition at line 16 of file stream.c.
References stream::comps, and new_list().
Referenced by main().
int read (stream * st, char * buf, int read_size)
This function attempts to read 'read_size' data from stream into a character buffer. The programmer is responsible for creating the buffer on which the data is to be written. The programmer is also responsible for destroying the buffer.
Parameters
st : the stream to be read from
buf : the buffer to be written to
read_size : number of bytes to be read
Returns
: the actual number of bytes read, -1 on error
if our compartment contained more data than was actually required, we need to copy back the remaining data back into our stream in a new compartment
Definition at line 44 of file stream.c.
References compartment::buffer, stream::comps, list_prepend(), list_remove_at_index(), list_size(), compartment::size, and STATUS_ERR.
Referenced by main().
int write (stream * st, const char * buf, int buf_size)
This function writes a buffer into the stream
Parameters
st : the stream to be written into
buf : the buffer to be written into the stream
buf_size : the size to be written
Returns
: the number of bytes written successfully
Definition at line 25 of file stream.c.
References compartment::buffer, stream::comps, list_append(), compartment::size, and STATUS_ERR.
Referenced by main().