Week1.c.lists: tests2.c File Reference
tests2.c File Reference
#include <stddef.h>
#include "stdint.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <sys/time.h>
#include "list.h"
#include "props.h"
Data Structures
struct element
Macros
#define assert(cond, msg)
#define RANDOM_INSERT_SIZE 1000
#define PROP_TEST_SIZE 100000
Functions
unsigned long long nano_time ()
char * toString (int val)
void random_string_insert_test (struct list *list)
void random_struct_insert_test (struct list *list)
void basic_prop_test ()
void perf_prop_test ()
void run_all_tests ()
Macro Definition Documentation
#define assert (cond, msg)
Value:
{ \
  if (!(cond)) {\
    printf("FAILURE: %s",msg);\
    exit(-1);  \
  }\
}
Definition at line 18 of file tests2.c.
Referenced by basic_prop_test(), and perf_prop_test().
#define PROP_TEST_SIZE 100000
Definition at line 160 of file tests2.c.
Referenced by perf_prop_test().
#define RANDOM_INSERT_SIZE 1000
Definition at line 38 of file tests2.c.
Referenced by random_string_insert_test(), and random_struct_insert_test().
Function Documentation
void basic_prop_test ()
Definition at line 142 of file tests2.c.
References assert, parse_properties(), print_properties(), and properties::props.
unsigned long long nano_time ()
Definition at line 25 of file tests2.c.
Referenced by run_all_tests().
void perf_prop_test ()
Definition at line 161 of file tests2.c.
References assert, parse_properties(), PROP_TEST_SIZE, and properties::props.
void random_string_insert_test (struct list * list)
Definition at line 51 of file tests2.c.
References list_append(), list_element_at(), list_insert_before_index(), print_list(), RANDOM_INSERT_SIZE, and toString().
Referenced by run_all_tests().
void random_struct_insert_test (struct list * list)
Definition at line 98 of file tests2.c.
References list_append(), list_element_at(), list_insert_before_index(), print_list(), RANDOM_INSERT_SIZE, and element::val.
Referenced by run_all_tests().
void run_all_tests ()
Definition at line 169 of file tests2.c.
References nano_time(), new_list(), random_string_insert_test(), and random_struct_insert_test().
char* toString (int val)
Definition at line 41 of file tests2.c.
Referenced by random_string_insert_test().